<?php 

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Pricing\Helper\Data as CurrencyHelper;
use Hyva\HyvaShippingDhl\Magewire\NoNeighbor;
use Hyva\HyvaShippingDhl\ViewModel\Tooltip;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var NoNeighbor $magewire */
/** @var Tooltip $tooltip */
/** @var CurrencyHelper $currency */
$tooltip = $viewModels->require(Tooltip::class);
$currency = $this->helper(CurrencyHelper::class);
$feenote = __('This service will incur additional shipping costs of $1 including VAT.')->render();
$feenote = str_replace('$1', $currency->currency($magewire->fee, true, false), $feenote);
?>

<div>
    <div class="flex items-center mb-6">
        <h4 class="font-semibold">
            <?= $escaper->escapeHtml(__('No Neighbor Delivery: Discreet Dispatch')) ?>
        </h4>
        <?= $tooltip->render(__('Exclude an alternative delivery to the neighbor if you are not available when the delivery is made.')) ?>
    </div>
    <label class="inline-flex items-center gap-x-4 ml-4" 
           for="noNeighbor">
        <input wire:model="noNeighbor"
               x-data="{ disabled: $wire.entangle('disabled') }"
               type="checkbox"
               id="noNeighbor"
               class="field checkbox w-4 h-4 renderer-checkbox"
               :class="disabled ? 'disabled:opacity-50' : ''"
               x-bind:disabled="disabled"
               wire:click="$emitTo('checkout.shipping.method.dhlpaket_bestway_preferred_neighbor', 'refresh')"
        />  
        <span class="text-gray-700 hover:cursor-pointer">
            <?= $escaper->escapeHtml(__('Use No Neighbour Delivery Service')) ?>
        </span>
    </label> 
    <p class="text-sm ml-10 pl-2">
        <?= $escaper->escapeHtml($feenote); ?>
    </p>
</div>