<?php 

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Pricing\Helper\Data as CurrencyHelper;
use Hyva\ShippingDhlDe\Magewire\NoNeighbor;
use Hyva\ShippingDhlDe\ViewModel\Tooltip;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var NoNeighbor $magewire */
/** @var Tooltip $tooltip */
$tooltip = $viewModels->require(Tooltip::class);
/** @var FormatterViewModel $formatterViewModel */
$formatterViewModel = $viewModels->require(FormatterViewModel::class);

$feenote = __('This service will incur additional shipping costs of $1 including VAT.')->render();
$feenote = str_replace('$1', $formatterViewModel->currency($magewire->fee), $feenote);
?>
<div>
    <div class="flex items-center mb-6">
        <h4 class="font-semibold">
            <?= $escaper->escapeHtml(__('No Neighbor Delivery: Discreet Dispatch')) ?>
        </h4>
        <?= $tooltip->render(__('Exclude an alternative delivery to the neighbor if you are not available when the delivery is made.')) ?>
    </div>
    <label class="inline-flex items-center gap-x-4 ml-4" 
           for="noNeighbor">
        <input wire:model="noNeighbor"
               type="checkbox"
               id="noNeighbor"
               class="field checkbox w-4 h-4 renderer-checkbox"
        />
        <span class="text-gray-700 hover:cursor-pointer">
            <?= $escaper->escapeHtml(__('Use No Neighbour Delivery Service')) ?>
        </span>
    </label>
    <?php if ($magewire->fee > 0): ?>
        <p class="text-sm">
            <?= $escaper->escapeHtml($feenote); ?>
        </p>
    <?php endif; ?>
</div>