<?php 

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\NetresearchShippingUi\Magewire\ParcelPackstationModal;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ParcelPackstationModal $magewire */
/** @var Hyva\Theme\ViewModel\HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroIcons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$shippingAddress = [
    'countryCode' => $magewire->shippingAddress['country_id'] ?? 'DE',
    'city'        => $magewire->shippingAddress['city'] ?? '',
    'postalCode'  => $magewire->shippingAddress['postalCode'] ?? '',
    'street' => is_array($magewire->shippingAddress['street'] ?? '')
        ? ($magewire->shippingAddress['street'][0] ?? '')
        : trim((string) ($magewire->shippingAddress['street'] ?? ''))
];
?>
<div x-data="mapdata"
     class="w-full h-full relative"
     data-mapbox-token="<?= $escaper->escapeHtmlAttr($magewire->getMapboxApiToken()) ?>"
     data-shipping-address='<?= $escaper->escapeHtmlAttr(json_encode($shippingAddress)) ?>'>    
    <button class="absolute right-0 top-0 p-6 cursor-pointer" 
            wire:click="closeModal" 
            type="button">
        <?= /* @noEscape */ $heroicons->xHtml('visibility.postoffice', 20, 20) ?>
    </button>
    <div class="grid grid-cols-2 gap-4">
        <div class="col-span-12 md:col-span-6 field-wrapper field-type-text">
            <label for="shipping-country" 
                   class="font-semibold">
                <span><?= $escaper->escapeHtml(__('Country')) ?></span>
            </label>
            <select id="shipping-country" 
                    class="form-select w-full" 
                    name="<?= $escaper->escapeHtml(__('Country')) ?>"
                    @change="updateCountry">
                <option value="DE" selected>
                    <?= $escaper->escapeHtml(__('Germany')) ?>
                </option>
            </select>
        </div>
        <div class="col-span-12 md:col-span-6 field-wrapper field-type-text">
            <label for="shipping-city" 
                   class="font-semibold">
                <span><?= $escaper->escapeHtml(__('City')) ?></span>
            </label>
            <input type="text" 
                   class="w-full form-input" 
                   id="shipping-city" 
                   :value="address.city"
                   @input="setCity"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('City')) ?>" />
        </div>
        <div class="col-span-12 md:col-span-6 field-wrapper field-type-text">
            <label for="shipping-postalcode" 
                   class="font-semibold">
                <span><?= $escaper->escapeHtml(__('Postal Code')) ?></span>
            </label>
            <input type="text" 
                   class="w-full form-input" 
                   id="shipping-postalcode" 
                   :value="address.postalCode"
                   @input="setPostCode"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Postal Code')) ?>" />
        </div>
        <div class="col-span-12 md:col-span-6 field-wrapper field-type-text">
            <label for="shipping-street" 
                   class="font-semibold">
                <span><?= $escaper->escapeHtml(__('Street')) ?></span>
            </label>
            <input type="text" 
                   class="w-full form-input" 
                   id="shipping-street" 
                   :value="address.street"
                   @input="setStreet"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Street')) ?>" />
        </div>
        <div class="col-span-12">
            <button @click.prevent="searchLocations" 
                    class="btn btn-primary text-sm mr-auto">
                <span><?= $escaper->escapeHtml(__('Search')) ?></span>
            </button>
        </div>
    </div>

    <div class="relative bg-white mt-6">
        <div id="layer-control" 
             class="absolute right-0 top-0 mr-2 mt-2 z-10 flex flex-col gap-y-2">
            <label for="postoffice-checkbox" 
                   class="flex items-center gap-x-2 px-2 bg-white rounded-md">
                <input type="checkbox"
                       id="postoffice-checkbox"
                       :checked="visibility.postoffice"
                       data-layer-type="postoffice"
                       @change="onLayerToggle">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Dhl_Paket::images/icon-postoffice.png')); ?>" 
                     alt="<?= $escaper->escapeHtmlAttr(__('Postoffice')) ?>">
            </label>
            <label for="locker-checkbox" 
                   class="flex items-center gap-x-2 px-2 bg-white rounded-md">
                <input type="checkbox"
                       id="locker-checkbox"
                       :checked="visibility.locker"
                       data-layer-type="locker"
                       @change="onLayerToggle">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Dhl_Paket::images/icon-packstation.png')); ?>" 
                     alt="<?= $escaper->escapeHtmlAttr(__('Locker')) ?>">
            </label>
            <label for="servicepoint-checkbox" 
                   class="flex items-center gap-x-2 px-2 bg-white rounded-md">
                <input type="checkbox"
                       id="servicepoint-checkbox"
                       :checked="visibility.servicepoint"
                       data-layer-type="servicepoint"
                       @change="onLayerToggle">
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('Dhl_Paket::images/icon-parcelshop.png')); ?>" 
                     alt="<?= $escaper->escapeHtmlAttr(__('Servicepoint')) ?>">
            </label>
        </div>
        
        <div class="relative w-full h-[50vh] md:w-[50vw] rounded-lg">
            <div x-data="initMap" 
                 class="w-full h-full z-0" 
                 x-ref="map" 
                 id="map"></div>
            <template x-if="showParcelShops">
                <div class="absolute top-0 right-0 bottom-0 w-1/2 overflow-y-scroll shadow-2xl z-10 bg-white">
                    <div class="p-4 flex flex-col gap-6 z-1">
                        <button type="button" 
                                @click="onCloseParcelShopDetail" 
                                class="absolute right-0 top-0 m-4">
                            <?= /* @noEscape */ $heroicons->xHtml('visibility.postoffice', 20, 20) ?>
                        </button>
                        <template x-if="selectedLocation">
                            <div>
                                <p class="font-bold mb-3" x-text="selectedLocation.display_name"></p>
                                <p class="semi-bold"><?= $escaper->escapeHtml(__('Address') . ': ') ?></p>
                                <p x-text="selectedLocation.address.company"></p>
                                <p x-text="selectedLocation.address.street"></p>
                                <p class="inline">
                                    <span x-text="selectedLocation.address.postal_code"></span>
                                    <span class="ml-1" x-text="selectedLocation.address.city"></span>
                                </p>
                            </div>
                        </template>    
                        <template x-if="hasOpeningHours">
                            <div>
                                <p class="semi-bold"><?= $escaper->escapeHtml(__('Opening hours') . ': ') ?></p>
                                <template x-for="opening_hour in selectedLocation.opening_hours" 
                                          :key="opening_hour.day_of_week">
                                    <div class="flex gap-x-3">
                                        <span class="w-10" x-text="opening_hour.day_of_week"></span>
                                        <span>
                                            <template x-for="(time_frame, tfIndex) in opening_hour.time_frames" :key="tfIndex">
                                                <p class="flex flex-row gap-2">
                                                    <span x-text="time_frame.opens"></span>
                                                    <span>-</span>
                                                    <span x-text="time_frame.closes"></span>
                                                </p>
                                            </template>
                                        </span>
                                    </div>
                                </template>
                            </div>
                        </template>
                        <template x-if="hasServices">
                            <div>
                                <p class="semi-bold"><?= $escaper->escapeHtml(__('Services') . ': ') ?></p>
                                <ul>
                                    <template x-for="service in selectedLocation.services" :key="service">
                                        <li>
                                            <span x-text="service" 
                                                  class="inline-flex items-center rounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 ring-1 ring-inset ring-gray-500/10"></span>
                                        </li>
                                    </template>
                                </ul>
                            </div>    
                        </template>
                    </div>
                </div>
            </template>
            <div class="absolute top-0 w-full h-full bg-black/30 z-0" 
                 @click="onCloseParcelShopDetail"
                 x-show="showParcelShops"></div>
        </div>
    </div>
</div>