<?php 

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\ShippingDhlDe\Magewire\ParcelAnnouncement;
use Hyva\ShippingDhlDe\ViewModel\Tooltip;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ParcelAnnouncement $magewire */
/** @var Tooltip $tooltip */
$tooltip = $viewModels->require(Tooltip::class);
?>

<div>
    <div class="flex items-center mb-6">
        <h4 class="font-semibold">
            <?= $escaper->escapeHtml(__('Parcel Announcement')) ?>
        </h4>
        <?= $tooltip->render(__('Your e-mail address will be sent to DHL upon enabling, after which DHL will trigger a package announcement for your shipment. The e-mail address will exclusively be used for the announcement of this shipment.')) ?>
    </div>
    <label class="inline-flex items-center gap-x-4 ml-4" 
           for="parcelAnnouncement">
        <input id="parcelAnnouncement"
               class="field checkbox w-4 h-4 renderer-checkbox"
               type="checkbox" 
               wire:model="parcelAnnouncement" />
        <span class="text-gray-700 hover:cursor-pointer">
            <?= $escaper->escapeHtml(__('Enable DHL parcel notification')) ?>
        </span>            
    </label>      
</div>