<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\HyvaShippingDhl\Magewire\CheckoutOptions;
use Hyva\HyvaShippingDhl\ViewModel\Tooltip;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var PreferredNeighbor $magewire */
/** @var Tooltip $tooltip */
$tooltip = $viewModels->require(Tooltip::class);
?>

<div>
    <div class="flex flex-row items-start">
        <h4 class="font-semibold">
            <?= $escaper->escapeHtml(__('Preferred Neighbor: Delivery to a neighbor of your choice')) ?>
        </h4>
        <?= $tooltip->render(__('Declare a person in your immediate neighborhood whom we can hand out your parcel. This person should live in the same building, directly opposite or next door.')) ?>
    </div>    
    <div class="ml-4 mr-10 flex flex-col gap-y-4 mt-2"
         wire:init="init" 
         x-data="{ disabled: $wire.entangle('disabled') }">
        <div>
            <label for="preferred_neighbor_name">
                <span>
                    <?= $escaper->escapeHtml(__('Neighbor name')) ?>
                </span>
            </label>
            <input wire:model.lazy="preferredNeighborName"
                   type="text"
                   id="preferred_neighbor_name"
                   class="block w-full form-input grow renderer-text"
                   :class="disabled ? 'disabled:opacity-50' : ''"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('First name, last name of neighbor'))?>"
                   x-bind:disabled="disabled"
                   />
        </div>
        <div>
            <label for="preferred_neighbor_address">
                <span>
                    <?= $escaper->escapeHtml(__('Neighbor address')) ?>
                </span>
            </label>
            <input wire:model.lazy="preferredNeighborAddress"
                   id="preferred_neighbor_address"
                   class="block w-full form-input grow renderer-text"
                   :class="disabled ? 'disabled:opacity-50' : ''"
                   type="text"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Street, number, postal code, city'))?>"
                   x-bind:disabled="disabled"
                   />
        </div>    
    </div>
</div>