<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Pricing\Helper\Data as CurrencyHelper;
use Hyva\ShippingDhlDe\Magewire\GoGreenPlus;
use Hyva\ShippingDhlDe\ViewModel\Tooltip;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GoGreenPlus $magewire */
/** @var Tooltip $tooltip */
$tooltip = $viewModels->require(Tooltip::class);
/** @var FormatterViewModel $formatterViewModel */
$formatterViewModel = $viewModels->require(FormatterViewModel::class);

$feenote = __('This service will incur additional shipping costs of $1 including VAT.')->render();
$feenote = str_replace('$1', $formatterViewModel->currency($magewire->fee), $feenote);
?>

<div>
    <div class="flex items-center mb-6">
        <h4 class="font-semibold">
            <?= $escaper->escapeHtml(__('GoGreen Plus: Climate Neutral Shipping')) ?>
        </h4>
        <?= /* @noEscape */ $tooltip->render(__('Climate-neutral shipping with DHL GoGreen Plus. Available for domestic German shipments only.')) ?>
    </div>

    <label class="inline-flex items-center gap-x-4 ml-4"
           for="gogreen_plus_enabled">
        <input id="gogreen_plus_enabled"
               class="field checkbox w-4 h-4 renderer-checkbox"
               type="checkbox"
               wire:model="goGreenPlusEnabled" />
        <span class="text-gray-700 hover:cursor-pointer">
            <?= $escaper->escapeHtml(__('Enable GoGreen Plus')) ?>
        </span>
    </label>
    
    <?php if ($magewire->fee > 0): ?>
        <p class="text-sm">
            <?= $escaper->escapeHtml($feenote); ?>
        </p>
    <?php endif; ?>
</div>